"""Fill the generated blocks in REPORT.md from artifacts/findings.json.

Run: uv run python scripts/render_report.py

Prose stays hand-written; every number lives inside a
<!-- BEGIN:name --> ... <!-- END:name --> block that this script owns. The prose
can therefore never quote a figure the code did not produce, which is the defect
this replaces: the previous REPORT.md was hand-assembled from scratch runs, and
its headline table spliced three incompatible ones.

tests/test_report_matches.py re-renders and asserts the file is unchanged.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTIFACT = ROOT / "artifacts" / "findings.json"
REPORT = ROOT / "REPORT.md"


def pm(d, places=3):
    """mean +/- sd across seeds."""
    return f"{d['mean']:+.{places}f} +/- {d['sd']:.{places}f}"


def blocks(f):
    m = f["meta"]
    out = {}

    out["preamble"] = (
        f"All figures below: a one-year at-the-money call on a 100 underlying, zero rates\n"
        f"and dividends, 30% volatility, **{m['n_paths']:,} paths on a "
        f"{m['n_mon']}-step monitoring grid**, replicated across\n"
        f"**{len(m['seeds'])} seeds** ({', '.join(str(s) for s in m['seeds'])}) and reported as "
        f"mean +/- standard deviation over those\nseeds. Every frequency in a sweep runs on the "
        f"same Brownian-nested paths.\n\n"
        f"Generated by `scripts/report.py` at commit `{m['git_commit'][:8]}` "
        f"({m['python']}, numpy {m['numpy']}, scipy {m['scipy']}).")

    d = f["f1_discretisation"]
    out["f1"] = (
        f"| rehedges per year | {d['rehedges_sparse']:.0f} | {d['rehedges_dense']:.0f} |\n"
        f"|---|---|---|\n"
        f"| sd of terminal P&L | {d['sd_sparse']:.3f} | {d['sd_dense']:.3f} |\n\n"
        f"Fitted log-log slope **{pm(d['slope'], 4)}**, against the theoretical "
        f"{d['theory']}.\n\n"
        f"The uncertainty is the point of quoting it: the slope moves by about "
        f"{d['slope']['sd']:.3f}\nbetween seeds, so any digit beyond the third is noise.")

    d = f["f2_lockin"]
    out["f2"] = (
        f"Selling at {d['s_imp']:.0%} implied against {d['s_real']:.0%} realized, where "
        f"`BS(s_imp) - BS(s_real) = {d['edge']:.4f}`:\n\n"
        f"| hedged at | mean P&L | sd | P(profit) |\n|---|---|---|---|\n"
        f"| realized | {pm(d['at_realized']['mean'], 4)} | "
        f"{d['at_realized']['sd']['mean']:.4f} | "
        f"{d['at_realized']['prob_profit']['mean']:.1%} |\n"
        f"| implied | {pm(d['at_implied']['mean'], 4)} | "
        f"{d['at_implied']['sd']['mean']:.4f} | "
        f"{d['at_implied']['prob_profit']['mean']:.1%} |\n\n"
        f"Drift is pinned to {d['drift']}, without which the two means do not agree.")

    d = f["f3_attribution"]
    e1, e8 = d["hedged_every_step"], d["hedged_every_8th"]
    rs = d["residual_scaling"]
    out["f3"] = (
        f"| term | hedged every step | hedged every 8th step |\n|---|---|---|\n"
        f"| gamma | {e1['gamma']['mean']:+.3f} | {e8['gamma']['mean']:+.3f} |\n"
        f"| theta | {e1['theta']['mean']:+.3f} | {e8['theta']['mean']:+.3f} |\n"
        f"| max abs delta | {e1['max_abs_delta']['mean']:.2e} | "
        f"{e8['max_abs_delta']['mean']:.3f} |\n\n"
        f"The delta column is why both schedules are shown. Hedging every step at the mark\n"
        f"volatility makes that term **zero by construction**, not by measurement, so the\n"
        f"near-zero figure on the left establishes nothing on its own. At every eighth step\n"
        f"the same term is {e8['max_abs_delta']['mean']:.2f}, and the decomposition still closes.\n\n"
        f"Residual relative to the gamma term, as the grid refines:\n\n"
        + " | ".join(f"n={r['n_mon']}" for r in rs) + "\n"
        + "|".join(["---"] * len(rs)) + "\n"
        + " | ".join(f"{r['residual_over_gamma']:.4f}" for r in rs) + "\n\n"
        f"Third order in `dS`, so it falls by roughly half per fourfold refinement.")

    d = f["f4_jump_floor"]
    out["f4"] = (
        f"| | slope | sd ratio, dense over sparse |\n|---|---|---|\n"
        f"| GBM control | **{pm(d['gbm']['slope'], 3)}** | "
        f"{d['gbm']['sd_ratio']['mean']:.3f} |\n"
        f"| Merton jumps | **{pm(d['merton']['slope'], 3)}** | "
        f"{d['merton']['sd_ratio']['mean']:.3f} |\n\n"
        f"Jump parameters: intensity {d['jump_params']['lam']}/year, log jumps of mean "
        f"{d['jump_params']['mu_J']:.0%}\nand dispersion {d['jump_params']['s_J']:.0%}. "
        f"Terminal P&L skew {d['merton_skew']['mean']:+.2f} against "
        f"{f['f4_jump_floor']['gbm'].get('skew', 'about zero') if False else 'near zero'} "
        f"for the diffusion,\nworst path {d['merton_worst_z']['mean']:.1f} standard "
        f"deviations from the mean.")

    d = f["f5_schedules"]
    rows = "\n".join(
        f"| {name} | {r['pnl']['mean']:+.4f} | {r['sd']['mean']:.4f} | "
        f"{r['rehedges']['mean']:.1f} | {r['turnover']['mean']:.1f} |"
        for name, r in d["table"].items())
    u = d["u_curve"]
    ww = d["ww_minus_fixed"]
    out["f5"] = (
        f"At {d['cost_bps']:.0f} bps proportional cost:\n\n"
        f"| schedule | mean P&L | sd | rehedges | turnover |\n|---|---|---|---|---|\n"
        f"{rows}\n\n"
        f"Whalley-Wilmott against hedging every step, paired bootstrap: "
        f"**{ww['diff']:+.4f}** per option,\n95% interval "
        f"[{ww['ci_low']:+.4f}, {ww['ci_high']:+.4f}].\n\n"
        f"On the pure frequency sweep at {u['cost_bps']:.0f} bps the risk-adjusted objective "
        f"bottoms at\n**{u['argmin_point']:.0f} rehedges**, but a bootstrap over paths puts that "
        f"location anywhere in\n**[{u['argmin_ci'][0]:.0f}, {u['argmin_ci'][1]:.0f}]**. "
        f"The optimum is a region, not a point, and reporting it\nas a single number would "
        f"overstate what the experiment resolves.")

    d = f["f6_surface"]
    rows = "\n".join(
        f"| {lvl} vol pts | {v['unconstrained_arbitraged']} of {v['n_reps']} | "
        f"{v['constrained_arbitraged']} of {v['n_reps'] - v['refused']} | {v['refused']} | "
        + (f"{v['fit_cost_vol_points']:+.3f} |" if v['fit_cost_vol_points'] is not None
           else "n/a |")
        for lvl, v in sorted(d["noise_levels"].items(), key=lambda kv: float(kv[0])))
    out["f6"] = (
        f"Target slice verified admissible first: minimum Durrleman g = "
        f"**{d['target_min_durrleman_g']:+.4f}**,\nat-the-money implied vol "
        f"{d['target_atm_iv']:.1%}, {d['T']:.2f} years to expiry. With no noise the\n"
        f"calibrator recovers it to {d['noise_free_rmse_vol_points']:.5f} vol points.\n\n"
        f"| quote noise | unconstrained implying a negative density | constrained | refused | "
        f"fit cost |\n|---|---|---|---|---|\n{rows}\n\n"
        f"Both arms run the identical optimiser and differ only in the constraint set. An\n"
        f"earlier version polished only the constrained arm, which made this a comparison of\n"
        f"optimisers rather than of constraints and produced the impossible result that\n"
        f"constraining a fit improved it.")

    d = f["f7_market_making"]
    gams = sorted(d["sweep"], key=float)
    strats = [s_ for s_ in ("avellaneda_stoikov", "glft", "symmetric")
              if s_ in d["sweep"][gams[0]]]
    header = " | ".join(s_.replace("_", " ") for s_ in strats)
    rows = "\n".join(
        f"| {g} | " + " | ".join(
            f"{d['sweep'][g][s_]['ratio']['mean']:.2f} +/- "
            f"{d['sweep'][g][s_]['ratio']['sd']:.2f}" for s_ in strats) + " |"
        for g in gams)
    pw = d.get("pairwise", {})
    pw_rows = "\n".join(
        f"| {k.replace('_minus_', ' minus ').replace('_', ' ')} | {v['diff']:+.3f} | "
        f"[{v['ci_low']:+.3f}, {v['ci_high']:+.3f}] | "
        f"{'straddles zero' if v['straddles_zero'] else 'decisive'} |"
        for k, v in pw.items())
    he = d.get("horizon_effect", {})
    sk = d["skew_minus_control"]
    out["f7"] = (
        f"Mean P&L divided by its standard deviation, across risk aversions:\n\n"
        f"| risk aversion | {header} |\n"
        + "|---" * (len(strats) + 1) + "|\n" + rows + "\n\n"
        f"Paired differences in mean P&L, same paths:\n\n"
        f"| comparison | difference | 95% interval | |\n|---|---|---|---|\n{pw_rows}\n\n"
        + (f"The horizon term explains it. Avellaneda-Stoikov widens as the horizon\n"
           f"lengthens, quoting {he['as_spread_far']:.3f} total at one year against "
           f"{he['as_spread_near']:.3f} near expiry.\n"
           f"The steady-state form quotes {he['glft_spread']:.3f} regardless, because a "
           f"dealer who keeps\nquoting has no horizon. The wider quote costs fills, and "
           f"the fills are the edge.\n" if he else ""))

    d = f.get("f8_inverse")
    if d:
        rows = "\n".join(
            f"| {r['spot']:.0f} | {r['coin_delta']:.6f} | {r['naive_delta']:.6f} | "
            f"{r['gap']:+.6f} | {r['gap_pct']:.1f}% |" for r in d["mismatch"])
        c8 = d["contract"]
        out["f8"] = (
            f"A coin-settled call, strike {c8['K']:.0f}, {c8['T']:.2f} years, "
            f"{c8['vol']:.0%} volatility. Coin price\n**{d['coin_price']:.6f}**, confirmed "
            f"by two independent routes:\n\n"
            f"| route | estimate | separation |\n|---|---|---|\n"
            f"| dollar payoff under Q, converted at spot | "
            f"{d['dollar_route']['mean']:.6f} +/- {d['dollar_route']['se']:.6f} | "
            f"{abs(d['dollar_route']['mean'] - d['coin_price']) / d['dollar_route']['se']:.2f} se |\n"
            f"| coin payoff under the share measure | "
            f"{d['share_route']['mean']:.6f} +/- {d['share_route']['se']:.6f} | "
            f"{abs(d['share_route']['mean'] - d['coin_price']) / d['share_route']['se']:.2f} se |\n\n"
            f"The naive quantity `E^Q[coin payoff]` is **{d['naive_expectation']:.6f}**, which is "
            f"not a\nprice and is not close to one. Jensen separates them.\n\n"
            f"Hedging error from converting a vanilla delta instead of differentiating the\n"
            f"coin price:\n\n"
            f"| spot | coin delta | converted vanilla | gap | gap |\n|---|---|---|---|---|\n"
            f"{rows}")

    c, v = f["convergence"], f["variance_reduction"]
    out["numerics"] = (
        f"**Convergence.** Standard error of the mean against sample size:\n\n"
        + " | ".join(f"n={r['n_paths']:,}" for r in c["rows"]) + "\n"
        + "|".join(["---"] * len(c["rows"])) + "\n"
        + " | ".join(f"{r['se']:.5f}" for r in c["rows"]) + "\n\n"
        f"Fitted slope {c['fitted_slope']:+.3f} against the expected "
        f"{c['expected_slope']}.\n\n"
        f"**Variance reduction.** The control variate is `{v['control']}`, which follows from\n"
        f"the same expansion as finding 1: correlation **{v['correlation']:+.3f}**, variance "
        f"ratio\n**{v['variance_ratio']:.3f}**, about {1 / v['variance_ratio']:.1f}x the "
        f"effective sample size at no cost.\n\n"
        f"Two negative results, both derived rather than discovered by tuning. The discounted\n"
        f"terminal payoff correlates with hedging P&L at only "
        f"{v['payoff_control_correlation']:+.3f} and buys nothing,\nbecause a working delta "
        f"hedge removes precisely the component of P&L that tracks the\nterminal value. And "
        f"antithetic sampling cannot help at all: the hedging error is even\nin the driving "
        f"normal, so a mirrored path reproduces it exactly and the correlation\nbetween a pair "
        f"is {v['antithetic_correlation']:.1f}.")
    d = f.get("f9_rough_vol_floor")
    if d:
        rows = "\n".join(
            f"| {eta} | {v['slope']['mean']:+.3f} +/- {v['slope']['sd']:.3f} | "
            f"{v['sd_ratio']['mean']:.3f} +/- {v['sd_ratio']['sd']:.3f} |"
            for eta, v in sorted(d["sweep"].items(), key=lambda kv: float(kv[0])))
        rc = d["roughness_control"]
        top = d["sweep"][str(max(d["etas"]))]
        out["f9"] = (
            f"Rough Bergomi with H = {d['H']} and correlation {d['rho']}, hedged with a "
            f"Black-Scholes delta:\n\n"
            f"| vol-of-vol eta | slope | sd dense / sd sparse |\n|---|---|---|\n{rows}\n\n"
            f"At eta = 0 the variance is constant, the model is Black-Scholes and the "
            f"square-root law\ncomes back. Raising it flattens the curve until rehedging "
            f"faster buys almost nothing.\n\n"
            f"Roughness is not what does it. At eta = {rc['eta']} and H = {rc['H']}, a "
            f"variance nearly as smooth as\na diffusion, the slope is "
            f"{rc['slope']['mean']:+.3f} and the ratio {rc['sd_ratio']['mean']:.3f}, "
            f"against {top['slope']['mean']:+.3f} and {top['sd_ratio']['mean']:.3f}\n"
            f"at H = {d['H']}. The floor is vega risk, and vega risk does not care how "
            f"rough the variance is.")

    d = f.get("f10_rough_skew")
    if d:
        rough, hes = d["models"]["rbergomi"], d["models"]["heston"]
        rows = "\n".join(
            f"| {T:.2f} | {rough['skews'][i]:.3f} | {hes['skews'][i]:.3f} |"
            for i, T in enumerate(d["maturities"]))
        out["f10"] = (
            f"At-the-money skew, measured as the implied volatility difference across "
            f"log-moneyness\n+/-{d['log_moneyness']:.2f}, divided by the width, on "
            f"{d['n_paths']:,} paths:\n\n"
            f"| maturity, years | rough Bergomi | Heston |\n|---|---|---|\n{rows}\n\n"
            f"Fitted power law in maturity: rough Bergomi **{rough['slope']:+.3f}**, "
            f"Heston {hes['slope']:+.3f},\nagainst the theoretical H - 1/2 = "
            f"{d['theoretical_slope']:+.2f}. A diffusive variance cannot make the "
            f"short-dated\nskew explode, whatever its parameters: its increments are "
            f"too smooth to move the\ndistribution of a one-week option. Roughness can, "
            f"and that is what it is for.")

    d = f.get("f11_unwind")
    if d:
        labels = {"frictionless": "free unwind", "unwind": "unwind charged",
                  "informed": "informed flow", "both": "both frictions"}
        rows = []
        for key in ("frictionless", "unwind", "informed", "both"):
            row = d["table"][key]
            for s_ in ("symmetric", "avellaneda_stoikov", "glft"):
                v = row[s_]
                rows.append(
                    f"| {labels[key]} | {s_.replace('_', ' ')} | {v['pnl']['mean']:.2f} | "
                    f"{v['sd_vs_control']['mean']:.2f} | {v['unwind_paid']['mean']:.2f} | "
                    f"{v['end_inventory']['mean']:.1f} |")
        pw = "\n".join(
            f"| {labels[k]} | {v['diff']:+.3f} | [{v['ci_low']:+.3f}, {v['ci_high']:+.3f}] | "
            f"{'straddles zero' if v['straddles_zero'] else 'decisive'} |"
            for k, v in d["pairwise"].items())
        u = d["unwind"]
        out["f11"] = (
            f"Unwinding costs {u['liq_cost']} per unit plus {u['liq_impact']} per unit "
            f"squared, and informed\nflow is 30% of arrivals. Mean P&L over seeds:\n\n"
            f"| setting | strategy | P&L | sd / control | unwind paid | inventory at the close |\n"
            f"|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n\n"
            f"The steady-state quoter against the never-skewed control, paired on the same "
            f"paths:\n\n| setting | difference | 95% interval | |\n|---|---|---|---|\n{pw}\n\n"
            f"The control ends the session holding several times the inventory, and in the "
            f"idealised\nmodel it hands that inventory back at the mid for nothing. Charge "
            f"it what a dealer\nactually pays to get flat and the ranking changes sides.")

    d = f.get("f12_adverse_selection")
    if d:
        strats = ("symmetric", "avellaneda_stoikov", "glft")
        header = " | ".join(s_.replace("_", " ") for s_ in strats)
        rows = "\n".join(
            f"| {phi} | " + " | ".join(
                f"{d['table'][phi][s_]['markout_per_fill']['mean']:+.4f}" for s_ in strats) + " |"
            for phi in sorted(d["table"], key=float))
        toll = " | ".join(f"{d['toll'][s_]:.2f}" for s_ in strats)
        out["f12"] = (
            f"Mean markout per fill, {d['markout_steps']} steps after the trade, against the "
            f"mid at the\ntime of the fill. Negative is the market moving through the "
            f"dealer's quote:\n\n"
            f"| informed fraction phi | {header} |\n" + "|---" * (len(strats) + 1) + "|\n"
            + rows + "\n\n"
            f"P&L given up to the informed flow, price points per session:\n\n"
            f"| {header} |\n" + "|---" * len(strats) + "|\n"
            f"| {toll} |\n\n"
            f"The three quoting rules mark out within "
            f"{d['markout_spread']:.4f} of each other and give up within "
            f"{d['toll_spread']:.2f}\nof the same P&L. Leaning against inventory is "
            f"protection against holding the wrong\nposition, not against being picked "
            f"off: the quoting rule never sees the information,\nso it cannot avoid it. "
            f"Anything that does has to come from the flow itself.")

    d = f.get("f13_minimum_variance")
    if d:
        rows = "\n".join(
            f"| {name.replace('_', ' ')} | {d['table']['rough'][name]['mean']:.4f} "
            f"+/- {d['table']['rough'][name]['sd']:.4f} | "
            f"{d['table']['gbm'][name]['mean']:.4f} |"
            for name in ("plain", "min_variance", "sticky_sign"))
        out["f13"] = (
            f"Standard deviation of terminal P&L, hedging a one-year call on a "
            f"256-step grid,\nrough Bergomi against a GBM control:\n\n"
            f"| delta used | rough Bergomi | GBM |\n|---|---|---|\n{rows}\n\n"
            f"The minimum-variance adjustment, at a slope of {d['mv_optimum']}, cuts the "
            f"error by\n**{d['cut_by_min_variance']:.1%}**. The slope the smile's shape "
            f"suggests is {d['slope_the_smile_suggests']:+.5f}, from a fitted\n"
            f"at-the-money skew of {d['atm_skew']:+.4f}, and it has the opposite sign: "
            f"using it raises the\nerror by **{d['cost_of_the_wrong_sign']:.1%}**.\n\n"
            f"Under GBM the implied volatility never moves, so there is no vega risk for "
            f"the extra\nstock to hedge and every adjustment is pure noise. That is the "
            f"control which says the\ngain on the rough paths is hedging rather than "
            f"luck.")

    return out


def main():
    f = json.loads(ARTIFACT.read_text())
    text = REPORT.read_text()
    filled = blocks(f)
    missing = []
    for name, body in filled.items():
        pattern = re.compile(
            rf"<!-- BEGIN:{name} -->.*?<!-- END:{name} -->", re.S)
        if not pattern.search(text):
            missing.append(name)
            continue
        replacement = f"<!-- BEGIN:{name} -->\n{body}\n<!-- END:{name} -->"
        text = pattern.sub(lambda _m, r=replacement: r, text)
    REPORT.write_text(text)
    print(f"rendered {len(filled) - len(missing)} block(s) into REPORT.md")
    if missing:
        print(f"  no marker found for: {', '.join(missing)}")


if __name__ == "__main__":
    main()
