"""One guide per tab: what the page is for, why it exists, and a walkthrough.

Press g in the panel for the current tab's guide. docs/TUTORIAL.md is rendered
from the same text by scripts/render_tutorial.py, and a test fails if the two
disagree, so the tutorial on GitHub is the one in the panel.
"""

import textwrap
from dataclasses import dataclass


@dataclass(frozen=True)
class Guide:
    tab: str
    title: str
    purpose: str        # what the page is for
    intent: str         # why it exists, and what it is built to show
    steps: tuple        # things to try, each with what you should see
    exercises: tuple = ()


GUIDES = [
    Guide(
        "lessons", "Lessons: the thirteen findings",
        "The findings of the lab, one per entry: the question a desk would ask, "
        "the mechanism that answers it, what to do about it, and the numbers that "
        "were actually measured.",
        "Everything else in the panel is a tool; this page is what the tools "
        "found. The numbers are read live from artifacts/findings.json, which "
        "scripts/report.py writes and CI checks against REPORT.md, so no number "
        "here is typed by hand. Read a lesson, then go to the tab that produced it "
        "and make the number move yourself.",
        (
            "Move down the list with the arrows. Start with finding 1: the slope "
            "of -0.5 is the law every other hedging result is measured against.",
            "Read WHY before MEASURED. Try to predict the number from the "
            "mechanism, then check it.",
            "Finding 12 is the bridge to tab 8: if skewing quotes cannot protect "
            "against informed flow, something that sees the flow has to.",
        ),
    ),
    Guide(
        "price", "Price: Black-Scholes and coin-settled options",
        "Prices and greeks for a call and a put, the coin-settled (inverse) price "
        "that Deribit actually trades, and the call delta drawn against spot.",
        "Crypto options are margined and settled in the coin, not in dollars, and "
        "their delta is not the vanilla delta converted at spot. This page exists "
        "to make that gap visible (finding 8) before any hedging experiment "
        "assumes a delta.",
        (
            "Press r with the defaults: an at-the-money one-year call at 30% vol. "
            "The delta is a little above 0.5, not exactly 0.5, because of the "
            "volatility term in d1.",
            "Set K to 60, deep in the money, and rerun: the converted vanilla "
            "delta is off by about 40%. At K = 130 the gap shrinks to about 15%. "
            "A coin-settled book hedged with vanilla deltas is most wrong deep in "
            "the money.",
            "Set T to 0.05 and watch the delta curve sharpen into a step: gamma is "
            "concentrated near the strike close to expiry.",
        ),
    ),
    Guide(
        "surface", "Surface: is the smile a set of prices?",
        "Fits an SVI slice to a smile generated by a Heston model, with noise "
        "added, and draws the risk-neutral density the fit implies.",
        "A smile that fits the quotes well can still imply a negative "
        "probability somewhere, which means a butterfly with a negative price: "
        "free money on paper, and a broken surface in a pricer. The constrained "
        "fit rules that out at a small cost in fit (finding 6).",
        (
            "Press fit with the defaults. The density stays above zero and the "
            "last line says these are prices.",
            "Set noise to 3 and seed to 3, then press unconstrained. The density "
            "dips below zero and the last line flags it: the fit is closer to the "
            "quotes and the surface is arbitrageable.",
            "Press fit at the same noise and seed. The rmse rises by about a "
            "quarter of a vol point and the density is non-negative again; that "
            "rise is the price of consistency. Other seeds show it less often: "
            "noise does not always break the fit, which is why finding 6 counts "
            "fits rather than showing one.",
        ),
    ),
    Guide(
        "hedge", "Hedge: what delta hedging costs",
        "Sells one call, delta hedges it on a schedule you choose, and shows the "
        "distribution of the terminal P&L with a full explain: delta, gamma, "
        "theta, carry, costs and the residual.",
        "The hedging error of a discretely hedged option is the basic risk of an "
        "options book. This page lets you trade frequency against costs yourself "
        "and see where the P&L comes from, term by term, rather than as one "
        "number.",
        (
            "Run with every = 1, then every = 4. The histogram roughly doubles in "
            "width: the sd goes as one over the square root of the rehedge count.",
            "Set bps to 10 and compare every = 1 with every = 8. The finer schedule "
            "has the narrower histogram and the worse mean.",
            "Read the explain: gamma and theta nearly cancel, and the residual is "
            "what discrete hedging cannot see.",
        ),
        ("frequency", "costs"),
    ),
    Guide(
        "making", "Making: where to quote",
        "Three quoting rules, Avellaneda-Stoikov, GLFT and a symmetric control "
        "that never skews, run on identical simulated order flow and compared by "
        "paired bootstrap.",
        "Skewing quotes against inventory is the textbook way for a market maker "
        "to control risk. This page measures what it buys and what it costs, on "
        "paths the strategies share, so the comparison is sharp. It is a backtest "
        "on synthetic flow, which is exactly why tab 8 exists.",
        (
            "Run with gamma 0.1. Both skewed strategies have about half the "
            "control's sd; Avellaneda-Stoikov gives up a few points of mean for it "
            "and GLFT almost none.",
            "Set gamma to 1.0. Avellaneda-Stoikov's horizon term grows and its "
            "mean drops; GLFT holds up better (finding 7).",
            "Compare the end-inventory histograms: skew keeps the dealer near flat.",
        ),
        ("aversion", "informed", "pairing"),
    ),
    Guide(
        "engines", "Engines: C++ against the reference",
        "Times the C++ hedging engine against the NumPy reference on equal work "
        "and reports the largest relative difference in P&L.",
        "A fast engine is only useful if it is right. The NumPy code is the "
        "reference every finding was computed on; the C++ core has to reproduce it "
        "to a stated tolerance before its speed means anything. The engine never "
        "falls back silently, so a parity check cannot compare an engine with "
        "itself.",
        (
            "Press benchmark. The speedup column is the headline; the rel dPnL "
            "column is the reason to believe it, and should sit around 1e-13.",
            "If rel dPnL ever climbs far above round-off, the engines disagree and "
            "the speedup means nothing until the C++ is fixed.",
        ),
    ),
    Guide(
        "runs", "Runs: the ledger",
        "Every experiment run through vl run, with the config hash, the git "
        "commit, whether the tree was dirty, the RNG scheme and the library "
        "versions.",
        "Published finance results reproduce about half the time. The ledger is "
        "how this lab avoids joining them: a number that cannot say which code "
        "and which config produced it is not a result.",
        (
            "Register and run a config: vl register configs/discretisation.toml, "
            "then vl run configs/discretisation.toml. It appears here.",
            "Edit a parameter without re-registering and try vl run again: it is "
            "refused, because the hypothesis would change after the fact.",
        ),
    ),
    Guide(
        "book", "Book: does the backtest survive the queue? (lob-lab, Rust)",
        "Runs lob-lab's study on the Deribit order book you have recorded: how "
        "many more fills a fill-at-touch backtest hands out than a queue gives, "
        "across the unknowable assumption about cancellations, and whether order "
        "flow imbalance predicts the next move.",
        "Most market-making backtests assume you are filled whenever a trade "
        "prints at your price. On real data that roughly doubles the fills. This "
        "tab is the honest version of tab 5: the same question, on a real book, "
        "with the assumptions that cannot be checked reported as a range.",
        (
            "Read the first chart: however the cancels are assigned, fill-at-touch "
            "hands out well over one fill per queue fill.",
            "Read the second: bars above zero are horizons where imbalance beat a "
            "coin flip. Check how many moves each rests on before believing it.",
            "Record more data (make record in lob-lab) and press rerun: the tab "
            "keeps calling it a pipeline until seven days are in.",
        ),
        ("latency", "markout", "optimistic", "ofi"),
    ),
    Guide(
        "contracts", "Contracts: a digital is not N(d2) (contract-lab, OCaml)",
        "Prices a digital on a live BTC smile two ways, from one volatility and as "
        "a call spread on the smile, and shows the pricing identities and the "
        "term sheets of the contract algebra.",
        "A digital priced off N(d2) ignores the smile's slope. On a steep crypto "
        "smile the error is hundreds of basis points, always in the same "
        "direction. The algebra underneath prints every contract as a term sheet "
        "and prices each one on a lattice and by Monte Carlo, so both routes can "
        "be checked against each other.",
        (
            "Read the chart: the sign flips at the money, following the slope of "
            "the smile.",
            "Scroll to CHECKS: every lattice price sits next to its closed form, "
            "and Longstaff-Schwartz sits just under the lattice, as it should.",
            "Refit the slice with scripts/export_slice.py and press reprice: the "
            "table moves with the market.",
        ),
    ),
    Guide(
        "exercises", "Exercises: predict, then run",
        "Graded backtesting exercises. Each asks for a prediction first, then runs "
        "the real experiment and marks it, with the measurement and the mechanism.",
        "A backtest that confirms what you already believed teaches nothing. "
        "Committing to an answer before the number exists is the same discipline "
        "as a preregistration. The answers are not stored anywhere: each exercise "
        "reads its answer off the run, so on lob-lab it grades against your own "
        "recorded data.",
        (
            "Pick an exercise with the arrows and read the question.",
            "Press a, b, c or d to commit. The experiment runs and the verdict "
            "appears with what was measured and why.",
            "When you get one wrong, go to its tab and reproduce the number by hand.",
        ),
    ),
]

BY_TAB = {g.tab: g for g in GUIDES}


def _para(text, width, indent=""):
    return textwrap.fill(text, width, initial_indent=indent,
                         subsequent_indent=indent)


def guide_text(tab, width, exercise_titles=None):
    """The guide for one tab, hard-wrapped to `width` columns."""
    g = BY_TAB[tab]
    out = [g.title, "", "WHAT IT IS FOR", _para(g.purpose, width), "",
           "WHY IT EXISTS", _para(g.intent, width), "", "TRY THIS"]
    for i, step in enumerate(g.steps, 1):
        out.append(textwrap.fill(step, width, initial_indent=f"  {i}. ",
                                 subsequent_indent="     "))
    if g.exercises and exercise_titles:
        out += ["", "EXERCISES  in tab 0"]
        out += [f"  - {exercise_titles[k]}" for k in g.exercises]
    return "\n".join(out)


def tutorial_markdown(exercise_titles):
    """docs/TUTORIAL.md, from the same guides the panel shows."""
    out = [
        "# vol-lab tutorial",
        "",
        "<!-- Generated by scripts/render_tutorial.py from src/vollab/tui/guides.py."
        " Edit the guides, not this file. -->",
        "",
        "Open the panel with `vl view`. Every tab below has the same guide inside "
        "the panel: press `g` on it. Tabs 8 and 9 run the sibling repositories "
        "`lob-lab` and `contract-lab`; tab 0, the tenth, holds graded exercises.",
        "",
    ]
    for n, g in enumerate(GUIDES, 1):
        out += [f"## {n % 10}. {g.title}", "", g.purpose, "",
                f"**Why it exists.** {g.intent}", "", "**Try this.**", ""]
        out += [f"{i}. {s}" for i, s in enumerate(g.steps, 1)]
        if g.exercises:
            out += ["", "**Exercises** (tab 0): "
                    + "; ".join(exercise_titles[k] for k in g.exercises) + "."]
        out.append("")
    return "\n".join(out)
